name:                httw
version:             0.1.0.0
github:              "isovector/httw"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2021 Sandy Maguire"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/httw#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- bytestring
- hashable
- circuitry
- circus
- process
- clash-prelude
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-extra
- QuickCheck
- generic-arbitrary
- diagrams-lib
- diagrams-rasterific
- diagrams-core
- diagrams-contrib

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields
  - -Wmissing-deriving-strategies
  - -fplugin GHC.TypeLits.Extra.Solver
  - -fplugin GHC.TypeLits.KnownNat.Solver
  - -fplugin GHC.TypeLits.Normalise

default-extensions:
  - EmptyCase
  - PostfixOperators
  - TupleSections
  - NamedFieldPuns
  - BangPatterns
  - BinaryLiterals
  - HexFloatLiterals
  - NumericUnderscores
  - GADTSyntax
  - RankNTypes
  - TypeApplications
  - PolyKinds
  - ExistentialQuantification
  - TypeOperators
  - ConstraintKinds
  - ExplicitForAll
  - KindSignatures
  - NamedWildCards
  - ScopedTypeVariables
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ConstrainedClassMethods
  - InstanceSigs
  - TypeSynonymInstances
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - StandaloneDeriving
  - EmptyDataDeriving
  - DeriveLift
  - GeneralisedNewtypeDeriving
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - NumDecimals
  - ViewPatterns
  - PatternSynonyms
  - TypeFamilies
  - DeriveAnyClass
  - NoStarIsType
  - DataKinds
  - DefaultSignatures
  - TypeApplications
  - LambdaCase
  - OverloadedLabels
  - InstanceSigs
  - RoleAnnotations
  - NoMonomorphismRestriction

library:
  source-dirs: code/
